{# #############################################################################
# This file compiles to Dockerfile.
############################################################################ -#}
#
# This file compiled from Dockerfile.in.
#

{% set current_dockerfile_config = dockerfile.main -%}

FROM {{ current_dockerfile_config.base_image }}

{# #############################################################################
# Core configuration of the environment. We should always include these.
############################################################################ -#}
{% include 'base/environment.Dockerfile' %}

{% include 'base/apt-get-essentials.Dockerfile' %}

{# #############################################################################
# Different runtimes we may want to include.
#
# {% include 'base/python.Dockerfile' %}
# {% include 'base/ruby.Dockerfile' %}
# {% include 'base/node.Dockerfile' %}
############################################################################ -#}
{% include 'base/python.Dockerfile' %}
{% include 'base/ruby.Dockerfile' %}
{% include 'base/node.Dockerfile' %}

################################################################################
# Additional packages we need.
################################################################################
RUN apt-get -qq clean && \
    apt-get -qq update && \
    apt-get -qq install -y --no-install-recommends \
        gawk \
        rsync \
        sshpass \
    && \
    apt-get -qq clean

################################################################################
# Install Python packages.
################################################################################
COPY docker-jekyll-site/requirements3.txt /docker-jekyll-site-temp/requirements3.txt
RUN dos2unix /docker-jekyll-site-temp/requirements3.txt && \
    pip install -r /docker-jekyll-site-temp/requirements3.txt

################################################################################
# Install Ruby gems.
################################################################################
COPY docker-jekyll-site/Gemfile /docker-jekyll-site-temp/Gemfile
COPY docker-jekyll-site/Gemfile.lock /docker-jekyll-site-temp/Gemfile.lock
RUN dos2unix /docker-jekyll-site-temp/Gemfile && \
    dos2unix /docker-jekyll-site-temp/Gemfile.lock && \
    cd /docker-jekyll-site-temp && bundle install

################################################################################
# Install Node modules. We will need to link to these at runtime.
################################################################################
COPY docker-jekyll-site/npm-shrinkwrap.json /docker-jekyll-site-temp/npm-shrinkwrap.json
COPY docker-jekyll-site/package.json /docker-jekyll-site-temp/package.json
RUN dos2unix /docker-jekyll-site-temp/npm-shrinkwrap.json && \
    dos2unix /docker-jekyll-site-temp/package.json && \
    cd /docker-jekyll-site-temp && npm install

################################################################################
# From before-base.
################################################################################

# Port where we serve the files
EXPOSE 4000

# Volume where the site will persist
VOLUME ["/docker-jekyll-site/site"]

################################################################################
# Set up our entrypoint script.
################################################################################
COPY docker-jekyll-site/docker-jekyll-site-entrypoint.sh /docker-jekyll-site-entrypoint.sh
RUN dos2unix /docker-jekyll-site-entrypoint.sh && \
    chmod +x /docker-jekyll-site-entrypoint.sh

# Run the wrapper script
CMD ["/docker-jekyll-site-entrypoint.sh"]
{# This comment gives us a newline at the end of the generated file #}
